### ISSUE TITLE
Command \deflength interfering with other common libraries

### ISSUE THREAD

**Issue by Etienne-Gautier** [ES-Alexander/LaTeX-templates#13]
The \deflength command defined in Report-Template/ReportTemplate2.tex (and used in other places) is conflicting with a command defined in the very common package biblatex (or one of its dependencies). Consider using another name.

**Comment by ES-Alexander** [comment]
Replaced it with \defineLength in the latest commit. Thanks for letting me know :-)

**Comment by ES-Alexander** [comment]
Latest release now includes this fix
